### ISSUE TITLE
Add config option to disable reddit notifications

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#101]
**Describe the solution you'd like**
For debugging purposes it would be nice to have a config option to disable the reddit notifications (similar to the bots), e.g. when you don't have your tokens yet.
The infrastructure is already partially there, so this should be easy to implement.

**Comment by zachkont** [comment]
Isn't it enough if you don't provide the reddit token?

**Comment by TimJentzsch** [comment]
Yes, that also works, but this would be a cleaner way, omitting the warning. Works the same way for the bots.
