### ISSUE TITLE
Improve botlogger

### ISSUE THREAD

**Issue by zachkont** [GameFeeder/GameFeeder#113]
The botlogger label should be mandatory. 

Some kind of smart labeling would be ideal to avoid repeating the same label over and over again in one file. Maybe the filename can somehow be appended? Otherwise, maybe botlogger could be a class and each file can initialize its own instance with a fixed label bound to that instance? There's probably a better idea but the general request is to have a mandatory label that is defined once per file ideally.

**Comment by TimJentzsch** [comment]
Closed by #124 (I always forget).
