### ISSUE TITLE
Change CI to GitHub actions

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#114]
**Describe the solution you'd like**
We should discard Travis CI in favor of [GitHub Actions](https://github.com/features/actions).

**Comment by zachkont** [comment]
After some research it seems that GitHub Actions are super beta and I'm not sure if they are worth the effort yet. Until then we can use something like [buildkite](https://buildkite.com/) which can also help with deployments

**Comment by TimJentzsch** [comment]
Is buildkite worth the effort to change from Travis? I would just change to GitHub Actions because it's better integrated, not sure if we use enough features to justify a change.

**Comment by zachkont** [comment]
I think it is, travis doesn't give many options and it looks like it's gonna die so replacing it seems like the way to go

**Comment by zachkont** [comment]
Closed by https://github.com/GameFeeder/GameFeeder/pull/120 and https://github.com/GameFeeder/GameFeeder/pull/126
