### ISSUE TITLE
Add command to display current subscriptions

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#14]
**Describe the solution you'd like**
A command (e.g. `/subscriptions`) to display the current subscriptions for this channel.
For example, if a channel is subscribed to Artifact and Dota 2, the command would display something like this:
 
> You are subscribed to the following games:
> - Artifact
> - Dota 2

**Comment by zachkont** [comment]
This is supported by the `/settings` command
