### ISSUE TITLE
Fix duplicate CI checks

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#152]
**Describe the bug**
When you push on a PR, two checks of each type are triggered by GitHub Actions.

**To Reproduce**
1. Create a PR
2. Push to the PR branch

**Expected behavior**
Only one check of each type should be triggered.

**Screenshots**
![Duplicate GitHub Actions checks](https://user-images.githubusercontent.com/13908946/67236819-49894180-f44a-11e9-93e4-09a6255287d5.png)

**Comment by zachkont** [comment]
Note: this was intended - one check is for the new branch and the other is for the pull request. The former simply tests the HEAD of the branch while the latter tests the integration with the target of the merge.

However, I do agree that it's more verbose than it needs to and we only need the PR checks
