### ISSUE TITLE
Add command to look up Artifact cards

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#221]
**Command name:** `artifact card <card_name>`

**Description:**
Add a command to display useful information about Artifact cards. At first, the information can be represented by simple text, but later it should be composed into an image for better readability.
The data can be obtained via the [API](https://artifactwiki.com/wiki/Special:ApiSandbox) of the [Artifact Wiki](https://artifactwiki.com/wiki/Main_Page) using the [cargo tables](https://artifactwiki.com/wiki/Special:CargoTables).
The image can be composed via [canvas](https://discordjs.guide/popular-topics/canvas.html#setting-up-canvas).

**Comment by zachkont** [comment]
RIP Artifact
