### ISSUE TITLE
Handle missing permission

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#43]
**Describe the bug**
Currently, the bot returns an unhandled promise rejection if it doesn't have permission to write in a channel.

**To Reproduce**
1. Add the bot to a server
2. Remove the writing permission on a channel for the bot
3. Send the bot a command (e.g. `!sub d2`)
4. The bot will return an unhandled promise rejection

**Expected behavior**
The bot should handle the rejected promise or not try to write in the channel at all. If the channel is subscribed to the bot it should unsubscribe itself, to prevent errors in the future.

**Comment by zachkont** [comment]
Some error logs related to this:

```
2019-11-26 17:54:31 [Telegram]   error:  Failed to send notification to channel [id]
Error: ETELEGRAM: 400 Bad Request: chat not found 

2019-11-26 17:54:31 [Telegram]   error:  Failed to send notification to channel [id]:
Error: ETELEGRAM: 403 Forbidden: bot was blocked by the user 
```

It's worth mentioning that I don't see the unhandled promise rejection error any more but it may be unrelated

**Comment by TimJentzsch** [comment]
On a related note, the bot should properly handle being removed from servers or being blocked by a user. If necessary, the bot should unsubsribe those chats from all games.
