### ISSUE TITLE
Rework icon

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#44]
**Describe the solution you'd like**
The bot should have an icon that is not specific to a certain game. This would be shown on the servers and as the bot's avatar.

**Comment by TimJentzsch** [comment]
This is closely connected to #81.

**Comment by zachkont** [comment]
New icon is dope:

![GameFeeder S (1)](https://user-images.githubusercontent.com/17274058/94994237-124e6a80-059f-11eb-813c-8899a78d5311.png)
