### ISSUE TITLE
Use JSON with comments for the config files

### ISSUE THREAD

**Issue by TimJentzsch** [GameFeeder/GameFeeder#79]
**Describe the solution you'd like**
Upgrade the config files to JSON with comments and expand the example files with explainations.

**Comment by zachkont** [comment]
Afaik JSON files cannot have comments in them. We could do some kind of 
```json
{
  _comment1: "blabla",
  field1: "value",
}
```
kind of structure but I don't think it looks good.

We could change from JSON to yaml or .envs or some other kind of format that supports comments, but we would need to add the parser for that (library or custom)

**Comment by zachkont** [comment]
There is also this: https://json5.org/ but I am not sure if I prefer it over more common formats

**Comment by TimJentzsch** [comment]
This is also problematic with the init manager, I will close this for now until we find a better way to document the config files.
